force-app/main/default/objects/CopadoTips__c/CopadoTips__c.object-meta.xml
<CustomObject>
    <description>Copado Tip of the Day:  documentation, tips, tricks, process reminders or best practices</description>
    <label>Copado Tip</label>
    <nameField>
        <label>Copado Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Tips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CopadoTips__c/fields/DefaultTip__c.field-meta.xml
<CustomField>
    <fullName>DefaultTip__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set the Tip as the default for a set of time, when used with the Date field. Should reset at the end of the date/time set.</description>
    <inlineHelpText>Default Tip of the day for a set period of time.</inlineHelpText>
    <label>Default Tip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipEndTime__c.field-meta.xml
<CustomField>
    <fullName>TipEndTime__c</fullName>
    <description>Display the default Copado Tip record at this end Date/Time</description>
    <inlineHelpText>Display the default Copado Tip record at this End Date/Time</inlineHelpText>
    <label>Display Tip End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CopadoTipResetJob.cls
public class CopadoTipResetJob implements Queueable {
    public void execute(QueueableContext context) {
        
        Datetime nowUtc = Datetime.now();
        
        List<CopadoTips__c> tipsToReset = [
            SELECT Id, DefaultTip__c, TipEndTime__c
            FROM CopadoTips__c
            WHERE DefaultTip__c = true AND TipEndTime__c < :nowUtc
        ];

        if (!tipsToReset.isEmpty()) {
            for (CopadoTips__c tip : tipsToReset) {
                tip.DefaultTip__c = false;
            }
            try {
                update tipsToReset;
            } catch (DmlException e) {
                System.debug('Error updating Copado Tips: ' + e.getMessage());
            }
        }
    }
}