force-app/main/default/objects/CopadoTips__c/CopadoTips__c.object-meta.xml
<CustomObject>
    <description>Copado Tip of the Day:  documentation, tips, tricks, process reminders or best practices</description>
    <label>Copado Tip</label>
    <nameField>
        <label>Copado Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Tips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CopadoTips__c/fields/DefaultTip__c.field-meta.xml
<CustomField>
    <fullName>DefaultTip__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set the Tip as the default for a set of time, when used with the Date field. Should reset at the end of the date/time set.</description>
    <inlineHelpText>Default Tip of the day for a set period of time.</inlineHelpText>
    <label>Default Tip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipCategory__c.field-meta.xml
<CustomField>
    <fullName>TipCategory__c</fullName>
    <description>What category does your tip fall under?</description>
    <inlineHelpText>What category does your tip fall under?</inlineHelpText>
    <label>Tip Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Practice</fullName>
            </value>
            <value>
                <fullName>How-to&apos;s</fullName>
            </value>
            <value>
                <fullName>DevOps Process</fullName>
            </value>
            <value>
                <fullName>Copado Methodology</fullName>
            </value>
            <value>
                <fullName>Release Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipDescription__c.field-meta.xml
<CustomField>
    <fullName>TipDescription__c</fullName>
    <label>Tip Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipEndTime__c.field-meta.xml
<CustomField>
    <fullName>TipEndTime__c</fullName>
    <description>Display the default Copado Tip record at this end Date/Time</description>
    <inlineHelpText>Display the default Copado Tip record at this End Date/Time</inlineHelpText>
    <label>Display Tip End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipStartTime__c.field-meta.xml
<CustomField>
    <fullName>TipStartTime__c</fullName>
    <description>Display the default Copado Tip record at this start Date/Time</description>
    <inlineHelpText>Display the default Copado Tip record at this start Date/Time</inlineHelpText>
    <label>Display Tip Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CopadoTips__c/fields/TipURL__c.field-meta.xml
<CustomField>
    <fullName>TipURL__c</fullName>
    <formula>HYPERLINK(&quot;boot-spare8-1.lightning.force.com/&quot; &amp; Id, TipCount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TipURL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CopadoTipController.cls
public with sharing class CopadoTipController {    
    @AuraEnabled(cacheable=true)
    public static Map<String, CopadoTips__c> getTips() {
        Map<String, CopadoTips__c> tipMap = new Map<String, CopadoTips__c>();
        
        // Get the current system time
        Datetime currentDateTime = Datetime.now();

        // Debugging the current system time
        System.debug('Current system time in the desired format: ' + currentDateTime.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ'));

        // Query to get the default Copado Tip
        List<CopadoTips__c> defaultTips = [
            SELECT Id, Name, TipDescription__c, TipCategory__c, DefaultTip__c, TipStartTime__c, TipEndTime__c, TipURL__c
            FROM CopadoTips__c
            WHERE DefaultTip__c = TRUE
            AND TipStartTime__c <= :currentDateTime
            AND TipEndTime__c >= :currentDateTime
            LIMIT 1
        ];

        if (!defaultTips.isEmpty()) {
            tipMap.put('defaultTip', defaultTips[0]);
        } else {
            // Get the count of all copado tips
            Integer tipCount = [SELECT COUNT() FROM CopadoTips__c];

            if (tipCount > 0) {
                // Generate a random offset within the count of active tips
                Integer randomOffset = Integer.valueOf(Math.floor(Math.random() * tipCount));

                // Query for a random tip using the OFFSET clause
                List<CopadoTips__c> randomTips = [
                    SELECT Id, Name, TipDescription__c, TipCategory__c, TipURL__c, DefaultTip__c
                    FROM CopadoTips__c
                    LIMIT 1
                    OFFSET :randomOffset
                ];

                if (!randomTips.isEmpty()) {
                    tipMap.put('randomTip', randomTips[0]);
                }
            }
        }

        return tipMap;
    }

    @AuraEnabled
    public static void resetDefaultTip() {
        // Get the current system time
        Datetime currentDateTime = Datetime.now();

        // Debugging the current system time
        System.debug('Current system time in the desired format: ' + currentDateTime.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ'));

        List<CopadoTips__c> defaultTips = [
            SELECT Id, DefaultTip__c
            FROM CopadoTips__c
            WHERE DefaultTip__c = TRUE
            AND TipEndTime__c < :currentDateTime
        ];

        if (!defaultTips.isEmpty()) {
            for (CopadoTips__c tip : defaultTips) {
                tip.DefaultTip__c = FALSE;
            }
            update defaultTips;
        }
    }
}